/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ts_tsproxyd_TsproxydService */

#ifndef _Included_com_ts_tsproxyd_TsproxydService
#define _Included_com_ts_tsproxyd_TsproxydService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ts_tsproxyd_TsproxydService_TSPROXYD_NOTIFICATION_ID
#define com_ts_tsproxyd_TsproxydService_TSPROXYD_NOTIFICATION_ID 111L
/*
 * Class:     com_ts_tsproxyd_TsproxydService
 * Method:    loadNativeService
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ts_tsproxyd_TsproxydService_loadNativeService
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_ts_tsproxyd_TsproxydService
 * Method:    unloadNativeService
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ts_tsproxyd_TsproxydService_unloadNativeService
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ts_tsproxyd_TsproxydService
 * Method:    onStartNativeService
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ts_tsproxyd_TsproxydService_onStartNativeService
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_ts_tsproxyd_TsproxydService
 * Method:    onStopNativeService
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_ts_tsproxyd_TsproxydService_onStopNativeService
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
